### ISSUE TITLE
Add route to generate the Webhook body, given a `broadcastId`.

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit-conversations#142]
# Spec
- End point will be protected by Basic Auth.
- `broadcastId`is required.
    - If `broadcastId` doesn't exist, return an error.

# Tasks
- [x] Remove all Customer.io code used to support the `Backup solution` in #139. - PR #143.
- [x] Create `broadcast-settings` endpoint that generates a JSON response with all necessary settings to execute a new broadcast. - PR #151.
- [x] Update endpoint to documentation. - PR #143.
